import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { Footer } from '@/components/Footer'

const arimoSans = Montserrat({
  variable: '--font-montserrat-sans',
  subsets: ['latin', 'cyrillic']
})

export const metadata: Metadata = {
  title: 'Доставка товаров от поставщика до маркетплейсов',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${arimoSans.variable} antialiased`}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
